# Generated by Django 4.2.3 on 2023-07-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0003_book_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
