# Generated by Django 4.2.3 on 2023-07-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0005_cart_alter_book_author_alter_book_genre_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="complete",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="viewer.cart"
            ),
        ),
    ]
